### ISSUE TITLE
Integrate with regexp editors like https://regex101.com

### ISSUE THREAD

**Issue by josdejong** [davisjam/vuln-regex-detector#38]
Thanks for developing `vuln-regex-detector`, it's essential for me as a non-regexp-expert to be able to determine whether there are security issues in my regexp's or not.

I was just thinking: it could be really powerful to integrate this service in online regexp editors like https://regex101.com/. Just an idea.

**Comment by davisjam** [comment]
Thanks for the suggestion. I've contacted the folks at regexbuddy. Hadn't tried regex101.com yet. Are there any other resources you use along these lines?

**Comment by josdejong** [comment]
:+1: 

> Are there any other resources you use along these lines?

Not regarding regular expressions, but I guess a simple google search will give a summary of the most popular regexp editors.

**Comment by davisjam** [comment]
I contacted regex101. Thanks for the suggestion.
