### ISSUE TITLE
unsafe-1.json format?

### ISSUE THREAD

**Issue by karl0ss** [davisjam/vuln-regex-detector#69]
I am wanting to use your docker container, I am trying to work out what format my - 
unsafe-1.json
needs to be in?

Thanks

**Comment by davisjam** [comment]
Do the examples in the [test suite](https://github.com/davisjam/vuln-regex-detector/tree/master/bin/test) help?

**Comment by karl0ss** [comment]
Yeah I didn't notice them, I'm an idiot, thanks for your help.
