### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by manish-kumar9a9** [davisjam/vuln-regex-detector#72]
Input OK. pattern /^\d\d:\d\d:\d\d$/ config {"server":{"hostname":"toybox.cs.vt.edu","port":8000},"cache":{"type":"persistent","persistentDir":"/var/folders/j0/m23f4smx71q96s90ysyz9ftc0000gp/T/vuln-regex-detector-client-persistentCache"}}
promiseResult: data {"pattern":"^\\d\\d:\\d\\d:\\d\\d$","language":"javascript","requestType":"LOOKUP_ONLY"}
kvGetPersistent: getting result from /var/folders/j0/m23f4smx71q96s90ysyz9ftc0000gp/T/vuln-regex-detector-client-persistentCache/32292db5f82de494f4c0bfefa49caf72.json
Writing to req:
{"pattern":"^\\d\\d:\\d\\d:\\d\\d$","language":"javascript","requestType":"LOOKUP_ONLY"}
Error: Error: connect ETIMEDOUT 128.173.237.124:8000

**Comment by davisjam** [comment]
At the moment the Virginia Tech instance of the backend service is not up. The code is available and instructions to set up your own instance are in the repo.

Sorry for any inconvenience!

The regex you indicated, `/^\d\d:\d\d:\d\d$/`, will be evaluated in linear time by any regex engine.

**Comment by manish-kumar9a9** [comment]
@davisjam No any problem at all.

> The regex you indicated, /^\d\d:\d\d:\d\d$/, will be evaluated in linear time by any regex engine

Thanks for the clarifications.
